### ISSUE TITLE
Update title for satellite 6 capsule page

### ISSUE THREAD

**Issue by ntkathole** [RedHatInsights/curiosity-frontend#542] opened 2020-12-15 03:42 UTC
## Description
Update title for satellite 6 capsule page. Currently default string is displayed "Subscription Watch".

Related to #539 

### Expected behavior
Title as "Red Hat Satellite 6/Red Hat Satellite 6 Capsule"

#### Steps to reproduce
1. https://qa.cloud.redhat.com/beta/subscriptions/satellite-sw/capsule

### Additional context, version info
![Screenshot from 2020-12-15 09-08-52](https://user-images.githubusercontent.com/16951913/102168041-8ff2f880-3eb5-11eb-84cf-f0b0d7989448.png)

**Comment by ntkathole** [comment] 2020-12-16 03:52
@cdcabrera with above fix, we can see title "Red Hat Satellite 6" on capsule page also we see "satellite 6" in tooltip as well, it was "satellite 6 capsule" earlier. 
![Screenshot from 2020-12-16 09-18-12](https://user-images.githubusercontent.com/16951913/102302951-225fce80-3f80-11eb-8283-182b106891fc.png)

**Comment by cdcabrera** [comment] 2021-01-04 15:38
So this appears to be working as intended, we're using RHEL as the basis for comparison. @ntkathole can this issue be closed?

**Comment by ntkathole** [comment] 2021-01-04 15:47
We can close if that's expected. I was assuming https://qa.cloud.redhat.com/beta/subscriptions/satellite-sw/capsule has "Red Hat Satellite 6 capsule" and https://qa.cloud.redhat.com/beta/subscriptions/satellite-sw/all has "Red Hat Satellite 6"  in tooltip.

**Comment by cdcabrera** [comment] 2021-01-22 20:47
@ntkathole closing this one down since we've got the api related issue that overlaps #553

**Closed by cdcabrera** 2021-01-22 20:47 UTC
Labels: bug, env:dev
